const AMOUNT_OUT_OF_RANGE: felt252 = 'ZT_AMOUNT_TOO_LARGE';
const INVALID_BURN_AMOUNT: felt252 = 'ZT_INVALID_BURN_AMOUNT';
const INVALID_COLLATERALIZATION: felt252 = 'ZT_INVALID_COLLATERALIZATION';
const INVALID_MINT_AMOUNT: felt252 = 'ZT_INVALID_MINT_AMOUNT';
const INVALID_TRANSFER_AMOUNT: felt252 = 'ZT_INVALID_TRANSFER_AMOUNT';
const MINT_TO_ZERO: felt252 = 'ZT_MINT_TO_ZERO';
const NOT_MARKET: felt252 = 'ZT_NOT_MARKET';
const ZERO_ADDRESS: felt252 = 'ZT_ZERO_ADDRESS';
