on:
  push:
    branches:
      - master

name: Contract Artifacts (dev)
jobs:
  test:
    name: Push contract artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Generate artifacts
        run: |
          ./scripts/compile_with_docker.sh

      - name: "Set up deploy key for artifacts repo"
        uses: "webfactory/ssh-agent@v0.7.0"
        with:
          ssh-private-key: ${{ secrets.ARTIFACTS_DEV_KEY }}

      - name: Push artifacts
        run: |
          COMMIT_HASH="$(git log -1 --format="%H")"
          git clone --depth=1 "git@github.com:zkLend/zklend-contract-artifacts-dev" ./artifacts
          mkdir -p ./artifacts/v1-core
          cp -r ./build ./artifacts/v1-core/$COMMIT_HASH
          rm -rf ./artifacts/v1-core/latest
          (cd ./artifacts/v1-core/ && rm -rf ./latest && ln -s ./$COMMIT_HASH ./latest)
          cd ./artifacts
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "artifacts: add contract artifacts from CI"
          git push
